### ISSUE TITLE
node and node-static-auth recipes are vulnerable to timing attacks

### ISSUE THREAD

**Issue by thibaudcolas** [flawyte/now-basic-auth#4]
👋 thank you for making these recipes available, it’s been very helpful for me.

Just wanted to point out that both the `node` and `node-static-auth` examples are in theory vulnerable to a [timing attack](https://en.wikipedia.org/wiki/Timing_attack) to determine the login/password.

Here is how express-basic-auth fixed this: https://github.com/LionC/express-basic-auth/pull/21

For further reference, see also how Rails fixed the same issue in their basic auth check, and how that CVE is classified: https://github.com/rails/rails/commit/a6fa3960c3a149e83eb2ff057be4472a82958e3d.

**Comment by flawyte** [comment]
Hey @thibaudcolas, thank you very much for pointing this out and for all the info! I'll look into it asap.
